name: CI du Projet Permuted MNIST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Mettre en place Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les d‚pendances
      run: |
        python -m pip install --upgrade pip
        # S'assure que le requirements.txt est … la racine du projet
        pip install -r requirements.txt
        pip install pytest

    - name: Lancer les tests (Smoke Test)
      run: |
        # Lancer Pytest sur le dossier de tests
        pytest tests/
